spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/template
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth-id-google}
            client-secret: ${oauth-secret-google}
            scope: profile, email
          github:
            client-id: ${oauth-id-github}
            client-secret: ${oauth-secret-github}
            scope: user

app:
  auth:
    token-secret: ${token-secret}
    access-token-validity-in-ms: 900000
    refresh-token-validity-in-ms: 1209600000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
